name: Purge Cloudflare Cache

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    branches: [main]
    types: 
      - completed

jobs:
  purge-cloudflare-cache:
    name: Puge Cloudflare Cache
    runs-on: ubuntu-latest

    steps:
     - name: Purge CloudFlare cache
       uses: jakejarvis/cloudflare-purge-action@master
       env:
         CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_CDN_ZONE }}
         CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_AUTH_TOKEN }}
